New-NetFirewallRule -DisplayName "excel" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\excel.exe" -Action block
New-NetFirewallRule -DisplayName "excelcnv" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\excelcnv.exe" -Action block
New-NetFirewallRule -DisplayName "FIRSTRUN" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\FIRSTRUN.exe" -Action block
New-NetFirewallRule -DisplayName "misc" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\misc.exe" -Action block
New-NetFirewallRule -DisplayName "msohtmed" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\msohtmed.exe" -Action block
New-NetFirewallRule -DisplayName "msosrec" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\msosrec.exe" -Action block
New-NetFirewallRule -DisplayName "msosync" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\msosync.exe" -Action block
New-NetFirewallRule -DisplayName "msouc" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\msouc.exe" -Action block
New-NetFirewallRule -DisplayName "namecontrolserver" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\nameservercontrol.exe" -Action block
New-NetFirewallRule -DisplayName "orgchart" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\orgchart.exe" -Action block
New-NetFirewallRule -DisplayName "ospprearm" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\ospprearm.exe" -Action block
New-NetFirewallRule -DisplayName "pdfreflow" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\pdfreflow.exe" -Action block
New-NetFirewallRule -DisplayName "powerpnt" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\powerpnt.exe" -Action block
New-NetFirewallRule -DisplayName "pptico" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\pptico.exe" -Action block
New-NetFirewallRule -DisplayName "protocolhandler" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\protocolhandler.exe" -Action block
New-NetFirewallRule -DisplayName "selfcert" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\selfcert.exe" -Action block
New-NetFirewallRule -DisplayName "winword" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\winword.exe" -Action block
New-NetFirewallRule -DisplayName "wordconv" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\wordconv.exe" -Action block
New-NetFirewallRule -DisplayName "wordicon" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\wordicon.exe" -Action block
New-NetFirewallRule -DisplayName "xlicon" -Direction outbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\xlicon.exe" -Action block
New-NetFirewallRule -DisplayName "excel" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\excel.exe" -Action block
New-NetFirewallRule -DisplayName "excelcnv" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\excelcnv.exe" -Action block
New-NetFirewallRule -DisplayName "FIRSTRUN" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\firstrun.exe" -Action block
New-NetFirewallRule -DisplayName "misc" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\misc.exe" -Action block
New-NetFirewallRule -DisplayName "msohtmed" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\msohtmed.exe" -Action block
New-NetFirewallRule -DisplayName "msosrec" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\msorec.exe" -Action block
New-NetFirewallRule -DisplayName "msosync" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\msosync.exe" -Action block
New-NetFirewallRule -DisplayName "msouc" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\msouc.exe" -Action block
New-NetFirewallRule -DisplayName "namecontrolserver" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\namecontrolserver.exe" -Action block
New-NetFirewallRule -DisplayName "orgchart" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\orgchart.exe" -Action block
New-NetFirewallRule -DisplayName "ospprearm" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\ospprearm.exe" -Action block
New-NetFirewallRule -DisplayName "pdfreflow" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\pdfreflow.exe" -Action block
New-NetFirewallRule -DisplayName "powerpnt" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\powerpnt.exe" -Action block
New-NetFirewallRule -DisplayName "pptico" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\pptico.exe" -Action block
New-NetFirewallRule -DisplayName "protocolhandler" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\protocolhandler.exe" -Action block
New-NetFirewallRule -DisplayName "selfcert" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\selfcert.exe" -Action block
New-NetFirewallRule -DisplayName "winword" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\winword.exe" -Action block
New-NetFirewallRule -DisplayName "wordconv" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\wordconv.exe" -Action block
New-NetFirewallRule -DisplayName "wordicon" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\wordicon.exe" -Action block
New-NetFirewallRule -DisplayName "xlicon" -Direction inbound -Program "C:\Program Files (x86)\Microsoft Office\Office16\xlicon.exe" -Action block
